import type { TouristPlace } from "@/lib/map-types";

export interface WorldTouristPlace extends TouristPlace {
  country: string;
  region: string;
}

export const WORLD_REGIONS = [
  "All",
  "Asia",
  "Europe",
  "Americas",
  "Africa",
  "Oceania",
] as const;

export type WorldRegion = (typeof WORLD_REGIONS)[number];

export const WORLD_TOURIST_PLACES: WorldTouristPlace[] = [
  {
    id: "world-taj-mahal",
    name: "Taj Mahal",
    country: "India",
    region: "Asia",
    category: "attraction",
    lat: 27.1751,
    lng: 78.0421,
    rating: 4.8,
    reviewsCount: 28400,
    description: "Iconic ivory-white marble mausoleum and UNESCO World Heritage Site in Agra.",
    address: "Agra, Uttar Pradesh, India",
    openingHours: "6:00 AM – 6:30 PM",
  },
  {
    id: "world-eiffel",
    name: "Eiffel Tower",
    country: "France",
    region: "Europe",
    category: "attraction",
    lat: 48.8584,
    lng: 2.2945,
    rating: 4.7,
    reviewsCount: 45200,
    description: "Paris landmark offering panoramic views from its observation decks.",
    address: "Champ de Mars, Paris, France",
    openingHours: "9:30 AM – 11:45 PM",
  },
  {
    id: "world-colosseum",
    name: "Colosseum",
    country: "Italy",
    region: "Europe",
    category: "attraction",
    lat: 41.8902,
    lng: 12.4922,
    rating: 4.8,
    reviewsCount: 38900,
    description: "Ancient Roman amphitheatre and one of the world's most visited monuments.",
    address: "Rome, Italy",
    openingHours: "9:00 AM – 7:00 PM",
  },
  {
    id: "world-great-wall",
    name: "Great Wall of China",
    country: "China",
    region: "Asia",
    category: "attraction",
    lat: 40.4319,
    lng: 116.5704,
    rating: 4.7,
    reviewsCount: 32100,
    description: "Historic fortification stretching across northern China with scenic hiking sections.",
    address: "Badaling, Beijing, China",
    openingHours: "7:30 AM – 5:30 PM",
  },
  {
    id: "world-machu-picchu",
    name: "Machu Picchu",
    country: "Peru",
    region: "Americas",
    category: "attraction",
    lat: -13.1631,
    lng: -72.545,
    rating: 4.9,
    reviewsCount: 27600,
    description: "15th-century Incan citadel set high in the Andes Mountains.",
    address: "Cusco Region, Peru",
    altitude: "2,430m",
  },
  {
    id: "world-statue-liberty",
    name: "Statue of Liberty",
    country: "United States",
    region: "Americas",
    category: "attraction",
    lat: 40.6892,
    lng: -74.0445,
    rating: 4.7,
    reviewsCount: 41200,
    description: "Symbol of freedom on Liberty Island in New York Harbor.",
    address: "New York, NY, USA",
    openingHours: "8:30 AM – 4:30 PM",
  },
  {
    id: "world-sydney-opera",
    name: "Sydney Opera House",
    country: "Australia",
    region: "Oceania",
    category: "attraction",
    lat: -33.8568,
    lng: 151.2153,
    rating: 4.8,
    reviewsCount: 29800,
    description: "World-famous performing arts centre on Sydney Harbour.",
    address: "Bennelong Point, Sydney, Australia",
    openingHours: "9:00 AM – 5:00 PM",
  },
  {
    id: "world-pyramids-giza",
    name: "Pyramids of Giza",
    country: "Egypt",
    region: "Africa",
    category: "attraction",
    lat: 29.9792,
    lng: 31.1342,
    rating: 4.8,
    reviewsCount: 35600,
    description: "Ancient pyramid complex including the Great Pyramid of Khufu.",
    address: "Giza, Egypt",
    openingHours: "8:00 AM – 5:00 PM",
  },
  {
    id: "world-santorini",
    name: "Santorini Caldera",
    country: "Greece",
    region: "Europe",
    category: "viewpoint",
    lat: 36.3932,
    lng: 25.4615,
    rating: 4.9,
    reviewsCount: 22400,
    description: "Cliffside villages and sunset viewpoints over the Aegean Sea.",
    address: "Santorini, Greece",
  },
  {
    id: "world-bali-rice",
    name: "Tegallalang Rice Terraces",
    country: "Indonesia",
    region: "Asia",
    category: "viewpoint",
    lat: -8.4312,
    lng: 115.2794,
    rating: 4.6,
    reviewsCount: 18700,
    description: "Stunning rice paddies and walking trails in Ubud, Bali.",
    address: "Ubud, Bali, Indonesia",
    openingHours: "7:00 AM – 6:00 PM",
  },
  {
    id: "world-grand-canyon",
    name: "Grand Canyon",
    country: "United States",
    region: "Americas",
    category: "viewpoint",
    lat: 36.1069,
    lng: -112.1129,
    rating: 4.9,
    reviewsCount: 51200,
    description: "Massive canyon carved by the Colorado River with dramatic overlooks.",
    address: "Arizona, USA",
    openingHours: "24 hours",
  },
  {
    id: "world-mount-fuji",
    name: "Mount Fuji",
    country: "Japan",
    region: "Asia",
    category: "viewpoint",
    lat: 35.3606,
    lng: 138.7274,
    rating: 4.8,
    reviewsCount: 26800,
    description: "Japan's highest peak and sacred volcano with seasonal climbing routes.",
    address: "Honshu, Japan",
    altitude: "3,776m",
  },
  {
    id: "world-petra",
    name: "Petra",
    country: "Jordan",
    region: "Asia",
    category: "attraction",
    lat: 30.3285,
    lng: 35.4444,
    rating: 4.8,
    reviewsCount: 24100,
    description: "Ancient Nabataean city famous for its rock-cut architecture.",
    address: "Ma'an Governorate, Jordan",
    openingHours: "6:00 AM – 6:00 PM",
  },
  {
    id: "world-table-mountain",
    name: "Table Mountain",
    country: "South Africa",
    region: "Africa",
    category: "viewpoint",
    lat: -33.9628,
    lng: 18.4098,
    rating: 4.8,
    reviewsCount: 19300,
    description: "Flat-topped mountain overlooking Cape Town with cable car access.",
    address: "Cape Town, South Africa",
    openingHours: "8:00 AM – 6:00 PM",
  },
  {
    id: "world-angel-falls",
    name: "Angel Falls",
    country: "Venezuela",
    region: "Americas",
    category: "viewpoint",
    lat: 5.9701,
    lng: -62.5362,
    rating: 4.9,
    reviewsCount: 8900,
    description: "World's highest uninterrupted waterfall in Canaima National Park.",
    address: "Bolívar, Venezuela",
    altitude: "979m drop",
  },
  {
    id: "world-niagara",
    name: "Niagara Falls",
    country: "Canada",
    region: "Americas",
    category: "viewpoint",
    lat: 43.0962,
    lng: -79.0377,
    rating: 4.7,
    reviewsCount: 33400,
    description: "Famous waterfall system on the border of Ontario and New York.",
    address: "Ontario, Canada",
    openingHours: "24 hours",
  },
  {
    id: "world-burj-khalifa",
    name: "Burj Khalifa",
    country: "United Arab Emirates",
    region: "Asia",
    category: "attraction",
    lat: 25.1972,
    lng: 55.2744,
    rating: 4.8,
    reviewsCount: 36700,
    description: "World's tallest building with observation decks in Downtown Dubai.",
    address: "Dubai, UAE",
    openingHours: "10:00 AM – 11:00 PM",
  },
  {
    id: "world-christ-redeemer",
    name: "Christ the Redeemer",
    country: "Brazil",
    region: "Americas",
    category: "attraction",
    lat: -22.9519,
    lng: -43.2105,
    rating: 4.8,
    reviewsCount: 31200,
    description: "Art Deco statue atop Corcovado mountain overlooking Rio de Janeiro.",
    address: "Rio de Janeiro, Brazil",
    openingHours: "8:00 AM – 7:00 PM",
  },
  {
    id: "world-angkor-wat",
    name: "Angkor Wat",
    country: "Cambodia",
    region: "Asia",
    category: "attraction",
    lat: 13.4125,
    lng: 103.8667,
    rating: 4.9,
    reviewsCount: 28900,
    description: "Vast temple complex and the largest religious monument in the world.",
    address: "Siem Reap, Cambodia",
    openingHours: "5:00 AM – 5:30 PM",
  },
  {
    id: "world-serengeti",
    name: "Serengeti National Park",
    country: "Tanzania",
    region: "Africa",
    category: "camp",
    lat: -2.3333,
    lng: 34.8333,
    rating: 4.9,
    reviewsCount: 15600,
    description: "Renowned wildlife reserve famous for the Great Migration.",
    address: "Tanzania",
    openingHours: "6:00 AM – 6:00 PM",
  },
  {
    id: "world-matterhorn",
    name: "Matterhorn",
    country: "Switzerland",
    region: "Europe",
    category: "viewpoint",
    lat: 45.9763,
    lng: 7.6586,
    rating: 4.9,
    reviewsCount: 21400,
    description: "Iconic Alpine peak near Zermatt with hiking and ski terrain.",
    address: "Zermatt, Switzerland",
    altitude: "4,478m",
  },
  {
    id: "world-kyoto-temple",
    name: "Fushimi Inari Shrine",
    country: "Japan",
    region: "Asia",
    category: "attraction",
    lat: 34.9671,
    lng: 135.7727,
    rating: 4.8,
    reviewsCount: 27600,
    description: "Shinto shrine with thousands of vermillion torii gates in Kyoto.",
    address: "Kyoto, Japan",
    openingHours: "Open 24 hours",
  },
  {
    id: "world-banff",
    name: "Lake Louise",
    country: "Canada",
    region: "Americas",
    category: "viewpoint",
    lat: 51.4254,
    lng: -116.1773,
    rating: 4.9,
    reviewsCount: 19800,
    description: "Turquoise glacial lake in Banff National Park with mountain backdrop.",
    address: "Alberta, Canada",
    openingHours: "24 hours",
  },
  {
    id: "world-igazu",
    name: "Iguazu Falls",
    country: "Argentina",
    region: "Americas",
    category: "viewpoint",
    lat: -25.6953,
    lng: -54.4367,
    rating: 4.9,
    reviewsCount: 24300,
    description: "Spectacular waterfall system on the Argentina–Brazil border.",
    address: "Misiones, Argentina",
    openingHours: "8:00 AM – 6:00 PM",
  },
  {
    id: "world-uluru",
    name: "Uluru",
    country: "Australia",
    region: "Oceania",
    category: "attraction",
    lat: -25.3444,
    lng: 131.0369,
    rating: 4.8,
    reviewsCount: 17200,
    description: "Sacred sandstone monolith in Australia's Red Centre.",
    address: "Northern Territory, Australia",
    openingHours: "Sunrise – Sunset tours",
  },
  {
    id: "world-zermatt",
    name: "Zermatt Village",
    country: "Switzerland",
    region: "Europe",
    category: "camp",
    lat: 46.0207,
    lng: 7.7491,
    rating: 4.8,
    reviewsCount: 14300,
    description: "Car-free alpine resort town at the foot of the Matterhorn.",
    address: "Valais, Switzerland",
  },
  {
    id: "world-varanasi",
    name: "Varanasi Ghats",
    country: "India",
    region: "Asia",
    category: "attraction",
    lat: 25.3176,
    lng: 83.0104,
    rating: 4.6,
    reviewsCount: 12800,
    description: "Historic riverfront steps along the Ganges with cultural ceremonies.",
    address: "Varanasi, Uttar Pradesh, India",
    openingHours: "Open 24 hours",
  },
  {
    id: "world-kerala",
    name: "Kerala Backwaters",
    country: "India",
    region: "Asia",
    category: "viewpoint",
    lat: 9.4981,
    lng: 76.3388,
    rating: 4.7,
    reviewsCount: 11200,
    description: "Network of lagoons and canals ideal for houseboat cruises.",
    address: "Alleppey, Kerala, India",
  },
  {
    id: "world-goa",
    name: "Palolem Beach",
    country: "India",
    region: "Asia",
    category: "viewpoint",
    lat: 15.0104,
    lng: 74.0232,
    rating: 4.5,
    reviewsCount: 9800,
    description: "Scenic crescent beach in South Goa popular with tourists.",
    address: "Goa, India",
    openingHours: "Open 24 hours",
  },
  {
    id: "world-london-eye",
    name: "London Eye",
    country: "United Kingdom",
    region: "Europe",
    category: "attraction",
    lat: 51.5033,
    lng: -0.1196,
    rating: 4.6,
    reviewsCount: 38700,
    description: "Giant observation wheel on the South Bank of the River Thames.",
    address: "London, UK",
    openingHours: "11:00 AM – 6:00 PM",
  },
];
